version: "3.3"
   
services:
  app:
    container_name: app
    image: app:1.0
    tty: true
    volumes:
      - ./volumes:/home/redundant/django
    depends_on:
      - db
    expose:
      - 8000
  web:
    container_name: web
    image: web:1.0
    volumes:
      - ./configuration/web/conf.d:/etc/nginx/conf.d
      - ./volumes:/django
    ports:
      - 80:80
      - 443:443
    links:
      - db
    expose:
      - 8000
  db:
    container_name: pg
    image: postgres:12.4-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
