version: "3.3"
   
services:
  app:
    container_name: app
    image: app:1.0
    tty: true
    volumes:
      - ./volumes:/home/redundant/django
    expose:
      - 8000
  web:
    container_name: web
    image: web:1.0
    volumes:
      - ./configuration/web/conf.d:/etc/nginx/conf.d
      - ./volumes:/django
    ports:
      - 80:80
      - 443:443
    expose:
      - 8000
